# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_knitro <- function() {
    .Call('RcppKnitro_test_knitro', PACKAGE = 'RcppKnitro')
}

infbound <- function() {
    .Call('RcppKnitro_infbound', PACKAGE = 'RcppKnitro')
}

