# This file was generated by Rcpp::compileAttributes
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

test_knitro <- function() {
    .Call('KNITRO_test_knitro', PACKAGE = 'KNITRO')
}

infbound <- function() {
    .Call('KNITRO_infbound', PACKAGE = 'KNITRO')
}

